services:
    db:
        container_name: postgres
        image: postgres
        environment:
            POSTGRES_DB: customer
            POSTGRES_USER: nibras
            POSTGRES_PASSWORD: 1234
            PGDATA: /data/postgres
        volumes:
            - db:/data/postgres
        ports:
            - "5332:5432"
        networks:
            - db
        restart: unless-stopped

    amigoscode-api:
        container_name: amigoscode-api
        image: mnibras/amigoscode-api
        build:
            context: backend
            dockerfile: Dockerfile
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer
        ports:
            - "8181:8080"
        networks:
            - db
        depends_on:
            - db
        restart: unless-stopped

    amigoscode-react:
        container_name: amigoscode-react
        image: mnibras/amigoscode-react
        build:
            context: frontend/react
            dockerfile: Dockerfile
            args:
                api_base_url: http://localhost:8181
        ports:
            - "3001:5173"
        depends_on:
            - amigoscode-api
        restart: unless-stopped

networks:
    db:
        driver: bridge

volumes:
    db:
